env:
  es2021: true
  node: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
overrides: []
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - '@typescript-eslint'
rules:
  comma-dangle:
    - error
    - always-multiline
  indent:
    - off
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
  '@typescript-eslint/no-inferrable-types':
    - off
  '@typescript-eslint/indent':
    - error
    - 4
    - SwitchCase: 1
      ignoredNodes:
        - "PropertyDefinition[decorators]"
        - "TSUnionType"
        - 'FunctionExpression > .params[decorators.length > 0]'
        - 'FunctionExpression > .params > :matches(Decorator, :not(:first-child))'
        - 'ClassBody.body > PropertyDefinition[decorators.length > 0] > .key'
